//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selery.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Selery.Model.Entity.B2B;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class B2BEntities : DbContext
    {
        public B2BEntities()
            : base("name=B2BEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spSelectSponsorByType_Result> spSelectSponsorByType(Nullable<int> sponsorTypeID)
        {
            var sponsorTypeIDParameter = sponsorTypeID.HasValue ?
                new ObjectParameter("SponsorTypeID", sponsorTypeID) :
                new ObjectParameter("SponsorTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectSponsorByType_Result>("spSelectSponsorByType", sponsorTypeIDParameter);
        }
    }
}
