//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selery.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Selery.Model.Entity.Registration;
    
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistrationEntities : DbContext
    {
        public RegistrationEntities()
            : base("name=RegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spInsertUser_Result> spInsertUser(string firstName, string lastName, string email, Nullable<long> facebookID, byte[] password)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var facebookIDParameter = facebookID.HasValue ?
                new ObjectParameter("FacebookID", facebookID) :
                new ObjectParameter("FacebookID", typeof(long));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spInsertUser_Result>("spInsertUser", firstNameParameter, lastNameParameter, emailParameter, facebookIDParameter, passwordParameter);
        }
    
        public virtual ObjectResult<spSelectUserByEmail_Result> spSelectUserByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectUserByEmail_Result>("spSelectUserByEmail", emailParameter);
        }
    
        public virtual ObjectResult<spSelectUserByID_Result> spSelectUserByID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectUserByID_Result>("spSelectUserByID", userIDParameter);
        }
    
        public virtual ObjectResult<spFindUserByEmail_Result> spFindUserByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFindUserByEmail_Result>("spFindUserByEmail", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spLoginByEmail(string email, byte[] password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spLoginByEmail", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<spFindUserByFacebookID_Result> spFindUserByFacebookID(Nullable<long> facebookID)
        {
            var facebookIDParameter = facebookID.HasValue ?
                new ObjectParameter("FacebookID", facebookID) :
                new ObjectParameter("FacebookID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFindUserByFacebookID_Result>("spFindUserByFacebookID", facebookIDParameter);
        }
    
        public virtual ObjectResult<spSelectUserByFacebookID_Result> spSelectUserByFacebookID(Nullable<long> facebookID)
        {
            var facebookIDParameter = facebookID.HasValue ?
                new ObjectParameter("FacebookID", facebookID) :
                new ObjectParameter("FacebookID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectUserByFacebookID_Result>("spSelectUserByFacebookID", facebookIDParameter);
        }
    
        public virtual ObjectResult<spSelectActivity_Result> spSelectActivity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectActivity_Result>("spSelectActivity");
        }
    
        public virtual ObjectResult<spSelectGoal_Result> spSelectGoal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectGoal_Result>("spSelectGoal");
        }
    
        public virtual ObjectResult<spUserWeightInsert_Result> spUserWeightInsert(Nullable<int> userID, Nullable<decimal> weight)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUserWeightInsert_Result>("spUserWeightInsert", userIDParameter, weightParameter);
        }
    
        public virtual ObjectResult<spIsProfileComplete_Result> spIsProfileComplete(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spIsProfileComplete_Result>("spIsProfileComplete", userIDParameter);
        }
    
        public virtual ObjectResult<spSelectActivityByID_Result> spSelectActivityByID(Nullable<int> activityID)
        {
            var activityIDParameter = activityID.HasValue ?
                new ObjectParameter("ActivityID", activityID) :
                new ObjectParameter("ActivityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectActivityByID_Result>("spSelectActivityByID", activityIDParameter);
        }
    
        public virtual ObjectResult<spSelectGoalByID_Result> spSelectGoalByID(Nullable<int> goalID)
        {
            var goalIDParameter = goalID.HasValue ?
                new ObjectParameter("GoalID", goalID) :
                new ObjectParameter("GoalID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectGoalByID_Result>("spSelectGoalByID", goalIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spUserActivityInsert(Nullable<int> userID, Nullable<int> activityID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var activityIDParameter = activityID.HasValue ?
                new ObjectParameter("ActivityID", activityID) :
                new ObjectParameter("ActivityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spUserActivityInsert", userIDParameter, activityIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spUserRegistrationUpdate(Nullable<int> userID, Nullable<int> gender, Nullable<int> heighInt, Nullable<int> heighDecint, Nullable<System.DateTime> birthDate, Nullable<int> goalID, Nullable<decimal> bMI, Nullable<decimal> calories)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(int));
    
            var heighIntParameter = heighInt.HasValue ?
                new ObjectParameter("HeighInt", heighInt) :
                new ObjectParameter("HeighInt", typeof(int));
    
            var heighDecintParameter = heighDecint.HasValue ?
                new ObjectParameter("HeighDecint", heighDecint) :
                new ObjectParameter("HeighDecint", typeof(int));
    
            var birthDateParameter = birthDate.HasValue ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(System.DateTime));
    
            var goalIDParameter = goalID.HasValue ?
                new ObjectParameter("GoalID", goalID) :
                new ObjectParameter("GoalID", typeof(int));
    
            var bMIParameter = bMI.HasValue ?
                new ObjectParameter("BMI", bMI) :
                new ObjectParameter("BMI", typeof(decimal));
    
            var caloriesParameter = calories.HasValue ?
                new ObjectParameter("Calories", calories) :
                new ObjectParameter("Calories", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spUserRegistrationUpdate", userIDParameter, genderParameter, heighIntParameter, heighDecintParameter, birthDateParameter, goalIDParameter, bMIParameter, caloriesParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spUserProfileUpdate(Nullable<int> userID, Nullable<decimal> weight, Nullable<int> activityID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var weightParameter = weight.HasValue ?
                new ObjectParameter("Weight", weight) :
                new ObjectParameter("Weight", typeof(decimal));
    
            var activityIDParameter = activityID.HasValue ?
                new ObjectParameter("ActivityID", activityID) :
                new ObjectParameter("ActivityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spUserProfileUpdate", userIDParameter, weightParameter, activityIDParameter);
        }
    }
}
